console.log('There is no exercise better for the heart than reaching down and lifting people up.\' by John Holmes teaches us to help one another.')
console.log("Love is not patronizing and charity isn't about pity, it is about love. Charity and love are the same -- with charity you give love, so don't just give money but reach out your hand instead.")
console.log(10 === '10')
console.log(parseFloat('9.8') == 10, Math.round(parseFloat('9.8')) == 10)
let val1 = 'Python'; let val2 = 'jargon' ;console.log(val1.includes('on'), val2.includes('on'))
let val3 = 'I hope this course is not full of jargon.'; console.log(val3.includes('jargon'))
console.log(Math.floor(Math.random()*101))
let rand = Math.floor(Math.random()*101); console.log(rand > 50 ?  rand : rand+50);
console.log(Math.floor(Math.random()*256))
let val4 = 'JavaScript'; console.log(val4.charAt(Math.floor(Math.random()*10)))
console.log('1 1 1 1 1\n2 1 2 4 8\n3 1 3 9 27\n4 1 4 16 64\n5 1 5 25 125')
let val5 = 'You cannot end a sentence with because because because is a conjunction'; console.log(val5.slice(31, 54), val5.substr(31,24))